# SPDX-License-Identifier: GPL-3.0-or-later
"""Commodore DOS directory records are consumed one byte per call."""
import ctypes as c
from pathlib import Path
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
MORE, ENTRY, END, ERROR = range(4)


class Directory(c.Structure):
    _fields_ = [('phase', c.c_uint8), ('length', c.c_uint8),
                ('link_low', c.c_uint8), ('number_low', c.c_uint8),
                ('number_high', c.c_uint8), ('saw_header', c.c_uint8),
                ('saw_footer', c.c_uint8), ('line', c.c_uint8 * 64)]


class Entry(c.Structure):
    _fields_ = [('blocks', c.c_uint16), ('name_length', c.c_uint8),
                ('name', c.c_uint8 * 16), ('type', c.c_uint8 * 3),
                ('closed', c.c_uint8), ('locked', c.c_uint8)]


def line(blocks, text):
    return bytes((1, 1, blocks & 255, blocks >> 8)) + text + b'\0'


def virtual_drive_directory():
    """The exact fixed-width record layout generated by 1986 virtual_drive."""
    header = bytearray(b' ' * 32)
    header[:7] = bytes((1, 4, 1, 1, 0, 0, 0x12))
    header[7:25] = b'"UDEKS DISK      "'
    header[31] = 0
    records = bytearray(header)
    for name, blocks, filetype, closed, locked in (
            (b'HELLO', 12, b'PRG', True, False),
            (b'NOTES FOR UDEKS', 1, b'SEQ', False, True)):
        record = bytearray(b' ' * 32)
        record[:4] = bytes((1, 1, blocks, 0))
        quote = 5 + (blocks < 100) + (blocks < 10)
        record[quote] = ord('"')
        record[quote + 1:quote + 1 + len(name)] = name
        record[quote + 1 + len(name)] = ord('"')
        kind = quote + 1 + 17
        record[kind] = ord(' ') if closed else ord('*')
        record[kind + 1:kind + 4] = filetype
        record[kind + 4] = ord('<') if locked else ord(' ')
        record[31] = 0
        records += record
    footer = bytearray(b' ' * 31)
    footer[:4] = bytes((1, 1, 66, 0))
    footer[4:16] = b'BLOCKS FREE.'
    footer[29:31] = b'\0\0'
    return bytes(records + footer)


class CbmDirectoryTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.temp = tempfile.TemporaryDirectory()
        library = Path(cls.temp.name) / 'cbm_directory.so'
        subprocess.run(['cc', '-std=c99', '-Wall', '-Wextra', '-Werror',
                        '-shared', '-fPIC', '-I' + str(ROOT / 'include'),
                        str(ROOT / 'src/services/filesystem/cbm_directory.c'),
                        '-o', str(library)], check=True)
        cls.lib = c.CDLL(str(library))
        cls.lib.udeks_cbm_dir_init.argtypes = [c.POINTER(Directory)]
        cls.lib.udeks_cbm_dir_feed.argtypes = [c.POINTER(Directory), c.c_uint8,
                                              c.POINTER(Entry)]
        cls.lib.udeks_cbm_dir_feed.restype = c.c_uint8
        cls.lib.udeks_cbm_dir_finish.argtypes = [c.POINTER(Directory)]
        cls.lib.udeks_cbm_dir_finish.restype = c.c_uint8
        cls.lib.udeks_cbm_dir_encode.argtypes = [c.POINTER(Entry),
                                                c.POINTER(c.c_uint8), c.c_uint8]
        cls.lib.udeks_cbm_dir_encode.restype = c.c_uint8

    @classmethod
    def tearDownClass(cls):
        cls.temp.cleanup()

    def setUp(self):
        self.state = Directory()
        self.entry = Entry()
        self.lib.udeks_cbm_dir_init(c.byref(self.state))

    def feed(self, data):
        found = []
        for value in data:
            result = self.lib.udeks_cbm_dir_feed(c.byref(self.state), value,
                                                 c.byref(self.entry))
            if result == ENTRY:
                found.append((self.entry.blocks,
                              bytes(self.entry.name[:self.entry.name_length]),
                              bytes(self.entry.type), self.entry.closed,
                              self.entry.locked))
            else:
                self.assertEqual(result, MORE)
        return found

    def test_virtual_drive_records_feed_incrementally(self):
        stream = virtual_drive_directory()
        found = []
        for offset in range(0, len(stream), 7):
            found += self.feed(stream[offset:offset + 7])
        self.assertEqual(found, [(12, b'HELLO', b'PRG', 1, 0),
                                 (1, b'NOTES FOR UDEKS', b'SEQ', 0, 1)])
        self.assertEqual(self.lib.udeks_cbm_dir_finish(c.byref(self.state)), END)

    def test_padding_trimmed_but_interior_spaces_and_raw_petscii_preserved(self):
        stream = (b'\x01\x04' + line(0, b'\x12"DISK"') +
                  line(7, b'  "A B\xc1           " PRG') +
                  line(100, b'BLOCKS FREE.'))
        self.assertEqual(self.feed(stream), [(7, b'A B\xc1', b'PRG', 1, 0)])
        self.assertEqual(self.lib.udeks_cbm_dir_finish(c.byref(self.state)), END)

    def test_zero_free_blocks_and_filename_resembling_footer(self):
        stream = (b'\x01\x04' + line(0, b'"DISK"') +
                  line(1, b' "BLOCKS FREE." PRG') +
                  line(0, b'BLOCKS FREE.'))
        self.assertEqual(self.feed(stream),
                         [(1, b'BLOCKS FREE.', b'PRG', 1, 0)])
        self.assertEqual(self.lib.udeks_cbm_dir_finish(c.byref(self.state)), END)

    def test_exactly_sixteen_name_bytes_and_reject_seventeen(self):
        self.feed(b'\x01\x04' + line(0, b'"DISK"'))
        self.assertEqual(self.feed(line(2, b' "SIXTEEN-CHAR-NAM" PRG')),
                         [(2, b'SIXTEEN-CHAR-NAM', b'PRG', 1, 0)])
        self.lib.udeks_cbm_dir_init(c.byref(self.state))
        self.feed(b'\x01\x04' + line(0, b'"DISK"') + b'\x01\x01\x02\x00')
        for value in b' "SEVENTEEN-CHAR-NA" PRG':
            self.assertEqual(self.lib.udeks_cbm_dir_feed(
                c.byref(self.state), value, c.byref(self.entry)), MORE)
        self.assertEqual(self.lib.udeks_cbm_dir_feed(
            c.byref(self.state), 0, c.byref(self.entry)), ERROR)

    def test_explicit_zero_link_finishes_without_eoi(self):
        stream = (b'\x01\x04' + line(0, b'"DISK"') +
                  line(100, b'BLOCKS FREE.'))
        self.assertEqual(self.feed(stream), [])
        self.assertEqual(self.lib.udeks_cbm_dir_feed(
            c.byref(self.state), 0, c.byref(self.entry)), MORE)
        self.assertEqual(self.lib.udeks_cbm_dir_feed(
            c.byref(self.state), 0, c.byref(self.entry)), END)
        self.assertEqual(self.lib.udeks_cbm_dir_finish(c.byref(self.state)), END)

    def test_truncated_and_early_end_fail_closed(self):
        self.feed(b'\x01\x04' + line(0, b'"DISK"'))
        self.assertEqual(self.lib.udeks_cbm_dir_finish(c.byref(self.state)), ERROR)
        self.lib.udeks_cbm_dir_init(c.byref(self.state))
        self.feed(b'\x01\x04' + line(0, b'"DISK"'))
        self.assertEqual(self.lib.udeks_cbm_dir_feed(
            c.byref(self.state), 0, c.byref(self.entry)), MORE)
        self.assertEqual(self.lib.udeks_cbm_dir_feed(
            c.byref(self.state), 0, c.byref(self.entry)), ERROR)

    def test_oversized_or_malformed_file_line_fails_sticky(self):
        self.feed(b'\x01\x04' + line(0, b'"DISK"') + b'\x01\x01\x01\x00')
        for _ in range(64):
            self.assertEqual(self.lib.udeks_cbm_dir_feed(
                c.byref(self.state), ord('A'), c.byref(self.entry)), MORE)
        self.assertEqual(self.lib.udeks_cbm_dir_feed(
            c.byref(self.state), ord('B'), c.byref(self.entry)), ERROR)
        self.assertEqual(self.lib.udeks_cbm_dir_finish(c.byref(self.state)), ERROR)
        self.lib.udeks_cbm_dir_init(c.byref(self.state))
        self.feed(b'\x01\x04' + line(0, b'"DISK"') + b'\x01\x01\x01\x00')
        self.assertEqual(self.lib.udeks_cbm_dir_feed(
            c.byref(self.state), 0, c.byref(self.entry)), ERROR)

    def test_entry_encodes_existing_getdents_wire_record(self):
        self.feed(b'\x01\x04' + line(0, b'"DISK"'))
        self.assertEqual(self.feed(line(4, b' "HELLO" PRG')),
                         [(4, b'HELLO', b'PRG', 1, 0)])
        output = (c.c_uint8 * 24)(*([0xA5] * 24))
        self.assertEqual(self.lib.udeks_cbm_dir_encode(
            c.byref(self.entry), output, 6), 0)
        self.assertEqual(bytes(output), bytes([0xA5] * 24))
        self.assertEqual(self.lib.udeks_cbm_dir_encode(
            c.byref(self.entry), output, 24), 7)
        self.assertEqual(bytes(output[:7]), b'\x08\x05HELLO')
        self.assertEqual(bytes(output[7:]), bytes([0xA5] * 17))


if __name__ == '__main__':
    unittest.main()
