#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Wrap the linked scheduler page and tail in one boot-load envelope."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

LOAD_ADDRESS = 0x5000
PAGE_ADDRESS = 0x1C00
TAIL_ADDRESS = 0xC120
TAIL_LIMIT = 0xCE00
MAGIC = b"USOV"
ABI_MAJOR = 0
ABI_MINOR = 2
HEADER_SIZE = 20

SEGMENT = re.compile(
    r"^([A-Z][A-Z0-9]*)\s+([0-9A-Fa-f]{6})\s+"
    r"([0-9A-Fa-f]{6})\s+([0-9A-Fa-f]{6})\s+",
    re.MULTILINE,
)


def map_segments(text: str) -> dict[str, tuple[int, int, int]]:
    return {
        name: (int(start, 16), int(end, 16), int(size, 16))
        for name, start, end, size in SEGMENT.findall(text)
    }


def build_overlay(page: bytes, tail: bytes, map_text: str) -> tuple[bytes, str]:
    segments = map_segments(map_text)
    if "SCHEDULER" not in segments or "CODE" not in segments or "BSS" not in segments:
        raise ValueError("scheduler overlay map lacks SCHEDULER, CODE, or BSS")
    page_start, _page_end, page_size = segments["SCHEDULER"]
    code_start = segments["CODE"][0]
    bss_start, bss_end, bss_size = segments["BSS"]
    if page_start != PAGE_ADDRESS:
        raise ValueError(f"scheduler page starts at ${page_start:04X}, expected $1C00")
    if code_start != TAIL_ADDRESS:
        raise ValueError(f"scheduler tail starts at ${code_start:04X}, expected $C120")
    if len(page) < page_size:
        raise ValueError(
            f"scheduler page image is {len(page)} bytes; map requires at least {page_size}"
        )
    if len(page) > 0x0400:
        raise ValueError("scheduler page exceeds $1C00-$1FFF")
    if any(page[page_size:]):
        raise ValueError("scheduler page padding is not zero")
    if len(tail) != bss_start - code_start:
        raise ValueError(
            f"scheduler tail image is {len(tail)} bytes; map requires "
            f"{bss_start - code_start}"
        )
    if bss_size == 0 or bss_size > 0xFF or bss_end + 1 > TAIL_LIMIT:
        raise ValueError("scheduler BSS is empty, exceeds 255 bytes, or reaches $CE00")
    checksum = (sum(page) + sum(tail)) & 0xFFFF
    header = bytearray(MAGIC)
    header += bytes((ABI_MAJOR, ABI_MINOR))
    header += page_start.to_bytes(2, "little")
    header += len(page).to_bytes(2, "little")
    header += code_start.to_bytes(2, "little")
    header += len(tail).to_bytes(2, "little")
    header += bss_start.to_bytes(2, "little")
    header += bss_size.to_bytes(2, "little")
    header += checksum.to_bytes(2, "little")
    if len(header) != HEADER_SIZE:
        raise AssertionError("scheduler overlay header size drifted")
    payload = LOAD_ADDRESS.to_bytes(2, "little") + header + page + tail
    page_source = LOAD_ADDRESS + HEADER_SIZE
    tail_source = page_source + len(page)
    constants = (
        "; generated by tools/build_scheduler_overlay.py\n"
        f"SCHEDULER_OVERLAY_LOAD = ${LOAD_ADDRESS:04x}\n"
        f"SCHEDULER_OVERLAY_END = ${LOAD_ADDRESS + HEADER_SIZE + len(page) + len(tail):04x}\n"
        f"SCHEDULER_OVERLAY_HEADER_SIZE = ${HEADER_SIZE:02x}\n"
        f"SCHEDULER_OVERLAY_ABI_MAJOR = ${ABI_MAJOR:02x}\n"
        f"SCHEDULER_OVERLAY_ABI_MINOR = ${ABI_MINOR:02x}\n"
        f"SCHEDULER_OVERLAY_PAGE_SOURCE = ${page_source:04x}\n"
        f"SCHEDULER_OVERLAY_PAGE_SIZE = ${len(page):04x}\n"
        f"SCHEDULER_OVERLAY_TAIL_SOURCE = ${tail_source:04x}\n"
        f"SCHEDULER_OVERLAY_TAIL_DESTINATION = ${code_start:04x}\n"
        f"SCHEDULER_OVERLAY_TAIL_SIZE = ${len(tail):04x}\n"
        f"SCHEDULER_OVERLAY_BSS = ${bss_start:04x}\n"
        f"SCHEDULER_OVERLAY_BSS_SIZE = ${bss_size:02x}\n"
        f"SCHEDULER_OVERLAY_CHECKSUM = ${checksum:04x}\n"
    )
    return payload, constants


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("page", type=Path)
    parser.add_argument("tail", type=Path)
    parser.add_argument("map", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("constants", type=Path)
    args = parser.parse_args()
    try:
        payload, constants = build_overlay(
            args.page.read_bytes(), args.tail.read_bytes(),
            args.map.read_text(encoding="utf-8"),
        )
    except ValueError as error:
        raise SystemExit(f"cannot build scheduler overlay: {error}") from error
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(payload)
    args.constants.parent.mkdir(parents=True, exist_ok=True)
    args.constants.write_text(constants, encoding="utf-8")


if __name__ == "__main__":
    main()
