#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Bind the non-installed task-context proof to the active scheduler overlay."""

import re
import subprocess
import sys
from pathlib import Path

from gen_scheduler_overlay_imports import MAP_SYMBOL


EXPECTED = {
    "_udeks_lifecycle_apply": "02",
    "_udeks_scheduler_select_next": "02",
    "decsp2": "02",
    "ptr1": "01",
    "sp": "01",
}
SEGMENT = re.compile(
    r"^([A-Z][A-Z0-9]*)\s+([0-9A-Fa-f]{6})\s+"
    r"([0-9A-Fa-f]{6})\s+([0-9A-Fa-f]{6})\s+",
    re.MULTILINE,
)


def object_imports(path: Path) -> dict[str, str]:
    dump = subprocess.run(
        ["od65", "--dump-imports", str(path)],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    records = re.findall(
        r'Address size:\s+0x([0-9A-Fa-f]+).*?Name:\s*"([^"]+)"',
        dump,
        re.S,
    )
    imports: dict[str, str] = {}
    for size, name in records:
        size = size.lower().zfill(2)
        if name in imports and imports[name] != size:
            raise ValueError(f"{name}: conflicting import address sizes")
        imports[name] = size
    if imports != EXPECTED:
        raise ValueError(f"task-context imports drifted: {imports!r}")
    return imports


def overlay_segments(text: str) -> dict[str, tuple[int, int, int]]:
    return {
        name: (int(start, 16), int(end, 16), int(size, 16))
        for name, start, end, size in SEGMENT.findall(text)
    }


def overlay_exports(text: str) -> dict[str, tuple[int, str]]:
    marker = "Exports list by name:"
    end_marker = "Exports list by value:"
    if marker not in text or end_marker not in text:
        raise ValueError("scheduler overlay map has no complete export table")
    table = text.split(marker, 1)[1].split(end_marker, 1)[0]
    pattern = re.compile(MAP_SYMBOL.pattern.replace("RLZ|REA", "RLZ|REZ|REA"))
    return {
        name: (int(address, 16), kind)
        for name, address, kind in pattern.findall(table)
    }


def render(imports: dict[str, str], map_text: str) -> str:
    segments = overlay_segments(map_text)
    scheduler = segments.get("SCHEDULER", (0, 0, 0))
    if scheduler[0] != 0x1C00 or scheduler[1] >= 0x1FFA:
        raise ValueError("active scheduler page no longer leaves $1FFA-$1FFF")
    if segments.get("BSS", (0, 0, 0))[1] != 0xCDC2:
        raise ValueError("active scheduler tail no longer ends at $CDC2")
    exports = overlay_exports(map_text)
    lines = [
        "; Generated by tools/gen_task_context_imports.py; do not edit.",
        "; SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        '        .setcpu "6502"',
        "",
    ]
    for name in sorted(imports):
        size = imports[name]
        if name not in exports:
            raise ValueError(f"{name}: missing from scheduler overlay map")
        address, kind = exports[name]
        expected_kinds = {"RLZ", "REZ"} if size == "01" else {"RLA", "REA"}
        if kind not in expected_kinds:
            raise ValueError(
                f"{name}: map type {kind}, expected one of {sorted(expected_kinds)}"
            )
        directive = ".exportzp" if size == "01" else ".export"
        lines.append(f"        {directive} {name}")
        lines.append(f"{name} = ${address:04x}")
    lines.extend([
        "",
        "        .import __CODE_RUN__, __BSS_RUN__, __BSS_SIZE__",
        '        .assert __CODE_RUN__ = $cdc3, lderror, "task-context code moved"',
        '        .assert __BSS_RUN__ + __BSS_SIZE__ <= $cf00, lderror, "task-context binding overflow"',
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: gen_task_context_imports.py <context.o> <overlay.map> <out.s>", file=sys.stderr)
        return 2
    try:
        imports = object_imports(Path(sys.argv[1]))
        map_text = Path(sys.argv[2]).read_text(encoding="utf-8")
        Path(sys.argv[3]).write_text(render(imports, map_text), encoding="utf-8")
    except (OSError, subprocess.CalledProcessError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
