#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the private runtime bridge for the Tasking 0.1 overlay.

The lifecycle and request-policy objects are linked outside the resident
kernel but execute with its cc65 runtime.  Derive their external imports from
the objects, subtract providers exported by the overlay itself, and bind the
remainder only when the normal and panic resident maps agree on address and
address class.
"""

import re
import subprocess
import sys
from pathlib import Path

ZEROPAGE = "01"
ABSOLUTE = "02"
EXPECTED_EXTERNALS = 20
EXPECTED_ABSOLUTE = 17
EXPECTED_ZEROPAGE = 3
SYMBOL_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
MAP_SYMBOL = re.compile(
    r"(?<!\S)([A-Za-z_][A-Za-z0-9_]*)\s+"
    r"([0-9A-Fa-f]{6})\s+(RLA|RLZ|REA)(?!\S)"
)


def canonicalize(records: list[tuple[str, str]]) -> list[tuple[str, str]]:
    canonical: dict[str, str] = {}
    for name, size in records:
        if SYMBOL_NAME.fullmatch(name) is None:
            raise ValueError(f"unsafe symbol name {name!r}")
        size = size.lower()
        if size not in (ZEROPAGE, ABSOLUTE):
            raise ValueError(f"{name}: unsupported address size 0x{size}")
        if name in canonical and canonical[name] != size:
            raise ValueError(
                f"{name}: conflicting address types "
                f"0x{canonical[name]} and 0x{size}"
            )
        canonical[name] = size
    return sorted(canonical.items())


def object_records(path: str, section: str) -> list[tuple[str, str]]:
    dump = subprocess.run(
        ["od65", f"--dump-{section}", path],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    entries = re.findall(
        r'Address size:\s+0x([0-9A-Fa-f]+).*?Name:\s*"([^"]+)"',
        dump,
        re.S,
    )
    return canonicalize([(name, size) for size, name in entries])


def external_imports(objects: list[str]) -> list[tuple[str, str]]:
    imports: list[tuple[str, str]] = []
    exports: set[str] = set()
    for path in objects:
        imports.extend(object_records(path, "imports"))
        exports.update(name for name, _ in object_records(path, "exports"))
    external = [(name, size) for name, size in canonicalize(imports)
                if name not in exports]
    absolute = sum(size == ABSOLUTE for _, size in external)
    zeropage = sum(size == ZEROPAGE for _, size in external)
    if (len(external), absolute, zeropage) != (
        EXPECTED_EXTERNALS,
        EXPECTED_ABSOLUTE,
        EXPECTED_ZEROPAGE,
    ):
        raise ValueError(
            "expected overlay runtime contract "
            f"{EXPECTED_EXTERNALS} symbols "
            f"({EXPECTED_ABSOLUTE} absolute/{EXPECTED_ZEROPAGE} zero-page), "
            f"found {len(external)} ({absolute} absolute/{zeropage} zero-page)"
        )
    return external


def map_exports(text: str) -> dict[str, tuple[int, str]]:
    marker = "Exports list by name:"
    end_marker = "Exports list by value:"
    if marker not in text or end_marker not in text:
        raise ValueError("ld65 map has no complete by-name export table")
    table = text.split(marker, 1)[1].split(end_marker, 1)[0]
    exports: dict[str, tuple[int, str]] = {}
    for match in MAP_SYMBOL.finditer(table):
        name, address, kind = match.groups()
        value = (int(address, 16), kind)
        if name in exports and exports[name] != value:
            raise ValueError(f"{name}: conflicting definitions in linker map")
        exports[name] = value
    return exports


def resolve_bridge(
    imports: list[tuple[str, str]],
    normal: dict[str, tuple[int, str]],
    panic: dict[str, tuple[int, str]],
) -> list[tuple[str, str, int]]:
    resolved: list[tuple[str, str, int]] = []
    for name, size in imports:
        expected_kind = "RLZ" if size == ZEROPAGE else "RLA"
        if name not in normal:
            raise ValueError(f"{name}: missing from normal kernel map")
        if name not in panic:
            raise ValueError(f"{name}: missing from panic kernel map")
        if normal[name] != panic[name]:
            raise ValueError(
                f"{name}: normal/panic mismatch "
                f"{normal[name]} != {panic[name]}"
            )
        address, kind = normal[name]
        if kind != expected_kind:
            raise ValueError(f"{name}: map type {kind}, expected {expected_kind}")
        resolved.append((name, size, address))
    return resolved


def render_bridge(resolved: list[tuple[str, str, int]]) -> str:
    lines = [
        "; Generated by tools/gen_scheduler_overlay_imports.py; do not edit.",
        "; SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        '        .setcpu "6502"',
        "",
    ]
    for name, size, address in resolved:
        directive = ".exportzp" if size == ZEROPAGE else ".export"
        lines.append(f"        {directive} {name}")
        lines.append(f"{name} = ${address:04x}")
    lines.extend(
        [
            "",
            "        .import __SCHEDULER_RUN__, __SCHEDULER_SIZE__",
            "        .import __CODE_RUN__, __BSS_RUN__, __BSS_SIZE__",
            '        .assert __SCHEDULER_RUN__ = $1c00, lderror, "scheduler page moved"',
            '        .assert __SCHEDULER_SIZE__ <= $0400, lderror, "scheduler page overflow"',
            '        .assert __CODE_RUN__ = $c120, lderror, "scheduler tail moved"',
            '        .assert __BSS_RUN__ + __BSS_SIZE__ <= $cc00, lderror, "scheduler core reaches lifecycle handler"',
            "",
        ]
    )
    return "\n".join(lines)


def write_bridge(
    objects: list[str], normal_map: str, panic_map: str, output_path: str
) -> None:
    imports = external_imports(objects)
    normal = map_exports(Path(normal_map).read_text(encoding="utf-8"))
    panic = map_exports(Path(panic_map).read_text(encoding="utf-8"))
    resolved = resolve_bridge(imports, normal, panic)
    Path(output_path).write_text(render_bridge(resolved), encoding="utf-8")


def main() -> int:
    if len(sys.argv) < 7 or sys.argv[1] != "bridge" or "--maps" not in sys.argv:
        print(
            "usage: gen_scheduler_overlay_imports.py bridge "
            "OBJECT.o... --maps NORMAL.map PANIC.map OUTPUT.s",
            file=sys.stderr,
        )
        return 2
    separator = sys.argv.index("--maps")
    if separator < 3 or len(sys.argv) - separator != 4:
        print("bridge requires objects and exactly two maps plus output", file=sys.stderr)
        return 2
    try:
        write_bridge(
            sys.argv[2:separator],
            sys.argv[separator + 1],
            sys.argv[separator + 2],
            sys.argv[separator + 3],
        )
    except (OSError, subprocess.CalledProcessError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
