#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the private typed bridge for the boot-only console image."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

from gen_capability_imports import (
    ABSOLUTE,
    ZEROPAGE,
    canonicalize,
    map_exports,
    resolve_bridge,
)


EXPECTED_RECORDS = 18
EXPECTED_IMPORTS = 14
EXPECTED_ABSOLUTE = 12
EXPECTED_ZEROPAGE = 2
IMAGE_SIZE = 0x05AA
CODE_SIZE = 0x038F
RODATA_SIZE = 0x021B
DESTINATION = 0x1600
CAPABILITY_SIZE = 0x03C7
PROBE_STAGING_ADDRESS = 0xAD00
ACTIVATION_SIZE = 42


def object_imports(path: str) -> list[tuple[str, str]]:
    dump = subprocess.run(
        ["od65", "--dump-imports", path],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    records = re.findall(
        r'Address size:\s+0x([0-9A-Fa-f]+).*?Name:\s*"([^"]+)"',
        dump,
        re.S,
    )
    if len(records) != EXPECTED_RECORDS:
        raise ValueError(
            f"expected {EXPECTED_RECORDS} import records, found {len(records)}"
        )
    imports = canonicalize([(name, size.lower()) for size, name in records])
    absolute = sum(size == ABSOLUTE for _, size in imports)
    zeropage = sum(size == ZEROPAGE for _, size in imports)
    if len(imports) != EXPECTED_IMPORTS:
        raise ValueError(
            f"expected {EXPECTED_IMPORTS} unique imports, found {len(imports)}"
        )
    if absolute != EXPECTED_ABSOLUTE or zeropage != EXPECTED_ZEROPAGE:
        raise ValueError(
            f"expected {EXPECTED_ABSOLUTE} absolute/{EXPECTED_ZEROPAGE} "
            f"zero-page imports, found {absolute} absolute/{zeropage} zero-page"
        )
    return imports


def render_flags(imports: list[tuple[str, str]]) -> str:
    return " ".join(
        f"-u {name}" for name, size in imports if size == ABSOLUTE
    ) + "\n"


def render_bridge(resolved: list[tuple[str, str, int]]) -> str:
    lines = [
        "; Generated by tools/gen_boot_console_imports.py; do not edit.",
        "; SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        '        .setcpu "6502"',
        "",
    ]
    for name, size, address in resolved:
        directive = ".exportzp" if size == ZEROPAGE else ".export"
        lines.append(f"        {directive} {name}")
        lines.append(f"{name} = ${address:04x}")
    lines.extend(
        [
            "",
            "        .import _udeks_boot_console_build",
            "        .import __CODE_RUN__, __CODE_SIZE__",
            "        .import __RODATA_RUN__, __RODATA_SIZE__, __BSS_SIZE__",
            f'        .assert _udeks_boot_console_build = ${DESTINATION:04x}, lderror, "boot console entry moved"',
            f'        .assert __CODE_RUN__ = ${DESTINATION:04x}, lderror, "boot console code moved"',
            f'        .assert __CODE_SIZE__ = ${CODE_SIZE:04x}, lderror, "boot console code size drift"',
            f'        .assert __RODATA_RUN__ = ${DESTINATION + CODE_SIZE:04x}, lderror, "boot console rodata moved"',
            f'        .assert __RODATA_SIZE__ = ${RODATA_SIZE:04x}, lderror, "boot console rodata size drift"',
            '        .assert __BSS_SIZE__ = $0000, lderror, "boot console gained BSS"',
            "",
        ]
    )
    return "\n".join(lines)


def write_bridge(
    object_path: str, normal_map: str, panic_map: str, output_path: str
) -> None:
    imports = object_imports(object_path)
    normal = map_exports(Path(normal_map).read_text(encoding="utf-8"))
    panic = map_exports(Path(panic_map).read_text(encoding="utf-8"))
    resolved = resolve_bridge(imports, normal, panic)
    Path(output_path).write_text(render_bridge(resolved), encoding="utf-8")


def write_constants(
    image_path: str,
    boot_delivery_path: str,
    capability_path: str,
    capability_installer_path: str,
    activation_path: str,
    normal_map: str,
    panic_map: str,
    output_path: str,
) -> None:
    image = Path(image_path).read_bytes()
    boot_delivery = Path(boot_delivery_path).read_bytes()
    capability = Path(capability_path).read_bytes()
    capability_installer = Path(capability_installer_path).read_bytes()
    activation = Path(activation_path).read_bytes()
    if len(image) != IMAGE_SIZE:
        raise ValueError(
            f"boot console image is {len(image)} bytes, expected {IMAGE_SIZE}"
        )
    if len(boot_delivery) != 0x010B:
        raise ValueError(
            f"boot delivery image is {len(boot_delivery)} bytes; expected 267"
        )
    if len(capability) != CAPABILITY_SIZE:
        raise ValueError(
            f"capability image is {len(capability)} bytes, expected "
            f"{CAPABILITY_SIZE}"
        )
    if len(activation) != ACTIVATION_SIZE:
        raise ValueError(
            f"task-switch activation is {len(activation)} bytes, expected "
            f"{ACTIVATION_SIZE}"
        )
    normal = map_exports(Path(normal_map).read_text(encoding="utf-8"))
    panic = map_exports(Path(panic_map).read_text(encoding="utf-8"))
    name = "__VICSHADOW_RUN__"
    if name not in normal or name not in panic or normal[name] != panic[name]:
        raise ValueError("normal/panic VICSHADOW starts are missing or differ")
    shadow_start, kind = normal[name]
    if kind != "RLA":
        raise ValueError("VICSHADOW start is not an absolute label")
    source = (
        shadow_start + len(boot_delivery) + len(capability)
        + len(capability_installer)
    )
    installed_image = image + activation
    end = source + len(installed_image) - 1
    if end >= PROBE_STAGING_ADDRESS:
        raise ValueError(
            f"boot console staging ${source:04x}-${end:04x} reaches the "
            "probe staging page"
        )
    checksum = sum(installed_image) & 0xFFFF
    text = "\n".join(
        [
            "; Generated by tools/gen_boot_console_imports.py; do not edit.",
            "; SPDX-License-Identifier: GPL-3.0-or-later",
            f"BOOT_CONSOLE_STAGE_SOURCE = ${source:04x}",
            f"BOOT_CONSOLE_COMPOSER_SIZE = ${len(image):04x}",
            f"BOOT_CONSOLE_IMAGE_SIZE = ${len(installed_image):04x}",
            f"BOOT_CONSOLE_IMAGE_CHECKSUM = ${checksum:04x}",
            f"BOOT_CONSOLE_DESTINATION = ${DESTINATION:04x}",
            f"TASK_SWITCH_ACTIVATION_DESTINATION = ${DESTINATION + len(image):04x}",
            f"TASK_SWITCH_ACTIVATION_SIZE = ${len(activation):02x}",
            "",
        ]
    )
    Path(output_path).write_text(text, encoding="utf-8")


def main() -> int:
    try:
        if len(sys.argv) == 4 and sys.argv[1] == "flags":
            imports = object_imports(sys.argv[2])
            Path(sys.argv[3]).write_text(render_flags(imports), encoding="utf-8")
            return 0
        if len(sys.argv) == 6 and sys.argv[1] == "bridge":
            write_bridge(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
            return 0
        if len(sys.argv) == 10 and sys.argv[1] == "constants":
            write_constants(
                sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5],
                sys.argv[6], sys.argv[7], sys.argv[8], sys.argv[9]
            )
            return 0
    except (OSError, subprocess.CalledProcessError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    print(
        "usage:\n"
        "  gen_boot_console_imports.py flags <object> <out.txt>\n"
        "  gen_boot_console_imports.py bridge <object> <normal.map> "
        "<panic.map> <out.s>\n"
        "  gen_boot_console_imports.py constants <image> <boot-delivery> "
        "<capability> <cap-installer> <activation> <normal.map> <panic.map> "
        "<out.inc>",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
