#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Bind the post-bootstrap lifecycle handler to qualified scheduler images."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

from gen_scheduler_overlay_imports import MAP_SYMBOL


EXPECTED = {
    "_udeks_bootfs_finish_error": "02",
    "_udeks_bootfs_finish_ok": "02",
    "_udeks_lifecycle_current_private": "02",
    "_udeks_lifecycle_last_event_private": "02",
    "_udeks_lifecycle_rejected_private": "02",
    "_udeks_lifecycle_slots_private": "02",
    "_udeks_task_context_save_current": "02",
}


def object_imports(path: Path) -> dict[str, str]:
    dump = subprocess.run(
        ["od65", "--dump-imports", str(path)],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    records = re.findall(
        r'Address size:\s+0x([0-9A-Fa-f]+).*?Name:\s*"([^"]+)"',
        dump,
        re.S,
    )
    imports: dict[str, str] = {}
    for size, name in records:
        size = size.lower().zfill(2)
        if name in imports and imports[name] != size:
            raise ValueError(f"{name}: conflicting import address sizes")
        imports[name] = size
    if imports != EXPECTED:
        raise ValueError(f"task-YIELD imports drifted: {imports!r}")
    return imports


def map_exports(text: str) -> dict[str, tuple[int, str]]:
    marker = "Exports list by name:"
    end_marker = "Exports list by value:"
    if marker not in text or end_marker not in text:
        raise ValueError("ld65 map has no complete by-name export table")
    table = text.split(marker, 1)[1].split(end_marker, 1)[0]
    pattern = re.compile(MAP_SYMBOL.pattern.replace("RLZ|REA", "RLZ|REZ|REA"))
    return {
        name: (int(address, 16), kind)
        for name, address, kind in pattern.findall(table)
    }


def render(
    imports: dict[str, str], overlay_text: str, context_text: str,
    normal_text: str, panic_text: str,
) -> str:
    overlay = map_exports(overlay_text)
    context = map_exports(context_text)
    normal = map_exports(normal_text)
    panic = map_exports(panic_text)
    lines = [
        "; Generated by tools/gen_task_yield_imports.py; do not edit.",
        "; SPDX-License-Identifier: GPL-3.0-or-later",
        "",
        '        .setcpu "6502"',
        "",
    ]
    for name in sorted(imports):
        size = imports[name]
        if name == "_udeks_task_context_save_current":
            providers = context
        elif name in {"_udeks_bootfs_finish_error", "_udeks_bootfs_finish_ok"}:
            if normal.get(name) != panic.get(name):
                raise ValueError(f"{name}: normal/panic kernel maps differ")
            providers = normal
        else:
            providers = overlay
        if name not in providers:
            raise ValueError(f"{name}: missing from scheduler/context maps")
        address, kind = providers[name]
        expected = {"RLZ", "REZ"} if size == "01" else {"RLA", "REA"}
        if kind not in expected:
            raise ValueError(f"{name}: map type {kind}, expected {sorted(expected)}")
        directive = ".exportzp" if size == "01" else ".export"
        lines.append(f"        {directive} {name}")
        lines.append(f"{name} = ${address:04x}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 7:
        print(
            "usage: gen_task_yield_imports.py HANDLER.o OVERLAY.map "
            "CONTEXT.map NORMAL.map PANIC.map OUTPUT.s",
            file=sys.stderr,
        )
        return 2
    try:
        imports = object_imports(Path(sys.argv[1]))
        output = render(
            imports,
            Path(sys.argv[2]).read_text(encoding="utf-8"),
            Path(sys.argv[3]).read_text(encoding="utf-8"),
            Path(sys.argv[4]).read_text(encoding="utf-8"),
            Path(sys.argv[5]).read_text(encoding="utf-8"),
        )
        Path(sys.argv[6]).write_text(output, encoding="utf-8")
    except (OSError, subprocess.CalledProcessError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
